const api = {
  popular: `${process.env.NEXT_PUBLIC_API}/articles/popularArticles`,
  categories: `${process.env.NEXT_PUBLIC_API}/categories`,
  articles: `${process.env.NEXT_PUBLIC_API}/articles`,
  like: `${process.env.NEXT_PUBLIC_API}/articles/like/`,
  lunike: `${process.env.NEXT_PUBLIC_API}/articles/unlike/`,
  save: `${process.env.NEXT_PUBLIC_API}/articles/save/`,
  unsave: `${process.env.NEXT_PUBLIC_API}/articles/unsave/`,
  profile: `${process.env.NEXT_PUBLIC_API}/users/profile`,
  mostviewed: `${process.env.NEXT_PUBLIC_API}/user/mostViewedArticles`,
  violationReportCases: `${process.env.NEXT_PUBLIC_API}/violationReportCases/cases`,
  articleReport: `${process.env.NEXT_PUBLIC_API}/articles/report/`,
  articlePage: `${process.env.NEXT_PUBLIC_API}/articles/read/`,
  articleSearch: `${process.env.NEXT_PUBLIC_API}/articles/search?query=`,
  createArticle: `${process.env.NEXT_PUBLIC_API}/articles`,
  notifications: `${process.env.NEXT_PUBLIC_API}/notifications`,
  deleteCategory: `${process.env.NEXT_PUBLIC_API}/categories/`,
  createCategory: `${process.env.NEXT_PUBLIC_API}/categories`,
  editCategory: `${process.env.NEXT_PUBLIC_API}/categories/`,
  violationReports: `${process.env.NEXT_PUBLIC_API}/ViolationReports`,
  createViolationReportsCase: `${process.env.NEXT_PUBLIC_API}/violationReportCases/cases`,
  deleteViolationReportsCase: `${process.env.NEXT_PUBLIC_API}/violationReportCases/cases/`,
  editViolationReportsCase: `${process.env.NEXT_PUBLIC_API}/violationReportCases/cases/`,
  articleComments: `${process.env.NEXT_PUBLIC_API}/articles/comments/`,
  usersProfile: `${process.env.NEXT_PUBLIC_API}/users/profile/`,
  followUser: `${process.env.NEXT_PUBLIC_API}/users/follow/`,
};
export default api;
